"""empty message

Revision ID: 14633be58924
Revises: 1c862a88edce
Create Date: 2015-05-06 13:23:01.367560

"""

# revision identifiers, used by Alembic.
revision = '14633be58924'
down_revision = '1c862a88edce'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('fouls_commited', sa.SmallInteger(), nullable=True),
    sa.Column('fouls_suffered', sa.SmallInteger(), nullable=True),
    sa.Column('red_card', sa.SmallInteger(), nullable=True),
    sa.Column('yellow_card', sa.SmallInteger(), nullable=True),
    sa.Column('assists', sa.SmallInteger(), nullable=True),
    sa.Column('goals', sa.SmallInteger(), nullable=True),
    sa.Column('shots', sa.SmallInteger(), nullable=True),
    sa.Column('shots_goal', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['yt_match.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['yt_match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'match_football', sa.Column('match_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'match_football_ibfk_1', 'match_football', type_='foreignkey')
    op.create_foreign_key(None, 'match_football', 'yt_match', ['match_id'], ['id'])
    op.drop_column(u'match_football', 'mid')
    op.add_column(u'match_football_details', sa.Column('match_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'match_football_details_ibfk_1', 'match_football_details', type_='foreignkey')
    op.create_foreign_key(None, 'match_football_details', 'yt_match', ['match_id'], ['id'])
    op.drop_column(u'match_football_details', 'mid')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'match_football_details', sa.Column('mid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'match_football_details', type_='foreignkey')
    op.create_foreign_key(u'match_football_details_ibfk_1', 'match_football_details', 'yt_match', ['mid'], ['id'])
    op.drop_column(u'match_football_details', 'match_id')
    op.add_column(u'match_football', sa.Column('mid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'match_football', type_='foreignkey')
    op.create_foreign_key(u'match_football_ibfk_1', 'match_football', 'yt_match', ['mid'], ['id'])
    op.drop_column(u'match_football', 'match_id')
    op.drop_table('player_match')
    ### end Alembic commands ###
