"""empty message

Revision ID: 14e3bb39e6b8
Revises: 59dd64fce56b
Create Date: 2015-05-07 16:46:50.863294

"""

# revision identifiers, used by Alembic.
revision = '14e3bb39e6b8'
down_revision = '59dd64fce56b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'player_match_ibfk_2', 'player_match', type_='foreignkey')
    op.create_foreign_key(None, 'player_match', 'yt_player', ['player_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player_match', type_='foreignkey')
    op.create_foreign_key(u'player_match_ibfk_2', 'player_match', 'yt_match', ['player_id'], ['id'])
    ### end Alembic commands ###
