"""empty message

Revision ID: 156e1edee36
Revises: 1d48fb7b3fa6
Create Date: 2015-05-05 09:29:29.904221

"""

# revision identifiers, used by Alembic.
revision = '156e1edee36'
down_revision = '1d48fb7b3fa6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yt_player', 'age')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yt_player', sa.Column('age', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    ### end Alembic commands ###
