"""empty message

Revision ID: 1b52fe0cef13
Revises: 3251b0f959e9
Create Date: 2015-05-04 10:53:38.848569

"""

# revision identifiers, used by Alembic.
revision = '1b52fe0cef13'
down_revision = '3251b0f959e9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_number', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_number', sa.Column('id', mysql.INTEGER(display_width=11), nullable=False))
    ### end Alembic commands ###
