"""empty message

Revision ID: 1c4b1bca73bc
Revises: 75813aa30d8
Create Date: 2015-04-30 14:49:44.834134

"""

# revision identifiers, used by Alembic.
revision = '1c4b1bca73bc'
down_revision = '75813aa30d8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yt_league', sa.Column('espn_name', sa.String(length=60), nullable=True))
    op.add_column('yt_team', sa.Column('espn_name', sa.String(length=60), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yt_team', 'espn_name')
    op.drop_column('yt_league', 'espn_name')
    ### end Alembic commands ###
