"""empty message

Revision ID: 1c862a88edce
Revises: 1ef2f65f3fdf
Create Date: 2015-05-06 12:37:58.002978

"""

# revision identifiers, used by Alembic.
revision = '1c862a88edce'
down_revision = '1ef2f65f3fdf'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_football',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.SmallInteger(), nullable=True),
    sa.Column('away_score', sa.SmallInteger(), nullable=True),
    sa.Column('home_shots', sa.SmallInteger(), nullable=True),
    sa.Column('away_shots', sa.SmallInteger(), nullable=True),
    sa.Column('home_fouls', sa.SmallInteger(), nullable=True),
    sa.Column('away_fouls', sa.SmallInteger(), nullable=True),
    sa.Column('home_corner', sa.SmallInteger(), nullable=True),
    sa.Column('away_corner', sa.SmallInteger(), nullable=True),
    sa.Column('home_offside', sa.SmallInteger(), nullable=True),
    sa.Column('away_offside', sa.SmallInteger(), nullable=True),
    sa.Column('home_ball_possession', sa.SmallInteger(), nullable=True),
    sa.Column('away_ball_possession', sa.SmallInteger(), nullable=True),
    sa.Column('home_yellow_card', sa.SmallInteger(), nullable=True),
    sa.Column('away_yellow_card', sa.SmallInteger(), nullable=True),
    sa.Column('home_red_card', sa.SmallInteger(), nullable=True),
    sa.Column('away_red_card', sa.SmallInteger(), nullable=True),
    sa.Column('home_saving', sa.SmallInteger(), nullable=True),
    sa.Column('away_saving', sa.SmallInteger(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['mid'], ['yt_match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_football_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.Column('min', sa.SmallInteger(), nullable=True),
    sa.Column('team', sa.SmallInteger(), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('player_a', sa.String(length=30), nullable=True),
    sa.Column('player_a_id', sa.Integer(), nullable=True),
    sa.Column('player_b', sa.String(length=30), nullable=True),
    sa.Column('player_b_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mid'], ['yt_match.id'], ),
    sa.ForeignKeyConstraint(['player_a_id'], ['yt_player.id'], ),
    sa.ForeignKeyConstraint(['player_b_id'], ['yt_player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'yt_match', sa.Column('m_time', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'yt_match', 'm_time')
    op.drop_table('match_football_details')
    op.drop_table('match_football')
    ### end Alembic commands ###
