"""empty message

Revision ID: 20bd1f97446f
Revises: 43deb60610ac
Create Date: 2015-05-05 15:08:18.143280

"""

# revision identifiers, used by Alembic.
revision = '20bd1f97446f'
down_revision = '43deb60610ac'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yt_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espn_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('finish', sa.SmallInteger(), nullable=True),
    sa.Column('home_score', sa.SmallInteger(), nullable=True),
    sa.Column('away_score', sa.SmallInteger(), nullable=True),
    sa.Column('home_id', sa.Integer(), nullable=True),
    sa.Column('away_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['away_id'], ['yt_team.id'], ),
    sa.ForeignKeyConstraint(['home_id'], ['yt_team.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['yt_league.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'league_team', 'league_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column(u'league_team', 'team_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text(u"'0'"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'league_team', 'team_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column(u'league_team', 'league_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text(u"'0'"))
    op.drop_table('yt_match')
    ### end Alembic commands ###
