"""empty message

Revision ID: 21c475a3fecc
Revises: 3727e4c166bc
Create Date: 2015-05-07 15:28:14.477734

"""

# revision identifiers, used by Alembic.
revision = '21c475a3fecc'
down_revision = '3727e4c166bc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_football', sa.Column('away_shot', sa.SmallInteger(), nullable=True))
    op.add_column('match_football', sa.Column('home_shot', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_football', 'home_shot')
    op.drop_column('match_football', 'away_shot')
    ### end Alembic commands ###
