"""empty message

Revision ID: 22f617650e85
Revises: 
Create Date: 2015-04-28 15:37:21.214841

"""

# revision identifiers, used by Alembic.
revision = '22f617650e85'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yt_league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('name_cn', sa.String(length=60), nullable=True),
    sa.Column('short_name', sa.String(length=30), nullable=True),
    sa.Column('short_name_cn', sa.String(length=30), nullable=True),
    sa.Column('is_cup', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yt_league')
    ### end Alembic commands ###
