"""empty message

Revision ID: 24d5b63b7e03
Revises: 22f617650e85
Create Date: 2015-04-29 10:43:04.258372

"""

# revision identifiers, used by Alembic.
revision = '24d5b63b7e03'
down_revision = '22f617650e85'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yt_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('name_en', sa.String(length=60), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('league_team',
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['yt_league.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['yt_team.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('league_team')
    op.drop_table('yt_team')
    ### end Alembic commands ###
