"""empty message

Revision ID: 2a578ca812f0
Revises: 24d5b63b7e03
Create Date: 2015-04-29 11:07:59.608980

"""

# revision identifiers, used by Alembic.
revision = '2a578ca812f0'
down_revision = '24d5b63b7e03'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yt_team', sa.Column('type', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yt_team', 'type')
    ### end Alembic commands ###
