"""empty message

Revision ID: 3614983064bc
Revises: 43a1f12e84bb
Create Date: 2015-06-11 16:17:39.129545

"""

# revision identifiers, used by Alembic.
revision = '3614983064bc'
down_revision = '43a1f12e84bb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
