"""empty message

Revision ID: 3727e4c166bc
Revises: 14633be58924
Create Date: 2015-05-07 10:18:02.667152

"""

# revision identifiers, used by Alembic.
revision = '3727e4c166bc'
down_revision = '14633be58924'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_match', sa.Column('offside', sa.SmallInteger(), nullable=True))
    op.drop_column('yt_league', 'espn_name')
    op.drop_column('yt_team', 'espn_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yt_team', sa.Column('espn_name', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('yt_league', sa.Column('espn_name', mysql.VARCHAR(length=60), nullable=True))
    op.drop_column('player_match', 'offside')
    ### end Alembic commands ###
