"""empty message

Revision ID: 39cef477fe93
Revises: 45aafceb0b68
Create Date: 2015-06-11 17:00:59.795891

"""

# revision identifiers, used by Alembic.
revision = '39cef477fe93'
down_revision = '45aafceb0b68'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
