"""empty message

Revision ID: 43a1f12e84bb
Revises: 535f112e8698
Create Date: 2015-05-18 11:28:56.582174

"""

# revision identifiers, used by Alembic.
revision = '43a1f12e84bb'
down_revision = '535f112e8698'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_football', 'date')
    op.drop_column('match_football', 'time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_football', sa.Column('time', mysql.TIME(), nullable=True))
    op.add_column('match_football', sa.Column('date', sa.DATE(), nullable=True))
    ### end Alembic commands ###
