"""empty message

Revision ID: 43deb60610ac
Revises: 156e1edee36
Create Date: 2015-05-05 09:35:25.961008

"""

# revision identifiers, used by Alembic.
revision = '43deb60610ac'
down_revision = '156e1edee36'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league_team', 'league_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('league_team', 'team_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league_team', 'team_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('league_team', 'league_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    ### end Alembic commands ###
