"""empty message

Revision ID: 45aafceb0b68
Revises: 3614983064bc
Create Date: 2015-06-11 16:57:48.079358

"""

# revision identifiers, used by Alembic.
revision = '45aafceb0b68'
down_revision = '3614983064bc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yt_player', sa.Column('letter', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yt_player', 'letter')
    ### end Alembic commands ###
