"""empty message

Revision ID: 4de72dd4dad9
Revises: 1b52fe0cef13
Create Date: 2015-05-04 11:01:34.367628

"""

# revision identifiers, used by Alembic.
revision = '4de72dd4dad9'
down_revision = '1b52fe0cef13'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_player',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['yt_player.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['yt_team.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'team_id')
    )
    op.drop_table('player_number')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_number',
    sa.Column('player_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('team_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('number', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player_id'], [u'yt_player.id'], name=u'player_number_ibfk_1'),
    sa.ForeignKeyConstraint(['team_id'], [u'yt_team.id'], name=u'player_number_ibfk_2'),
    sa.PrimaryKeyConstraint('player_id'),
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('team_player')
    ### end Alembic commands ###
