"""empty message

Revision ID: 535f112e8698
Revises: 14e3bb39e6b8
Create Date: 2015-05-14 15:01:41.722417

"""

# revision identifiers, used by Alembic.
revision = '535f112e8698'
down_revision = '14e3bb39e6b8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("yt_player", "birthday",
                    type_=mysql.DATE(),
                    existing_type=mysql.DATETIME())
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("yt_player", "birthday",
                    type_=mysql.DATETIME(),
                    existing_type=mysql.DATE())
    ### end Alembic commands ###
