"""empty message

Revision ID: 75813aa30d8
Revises: 2a578ca812f0
Create Date: 2015-04-30 10:47:16.699378

"""

# revision identifiers, used by Alembic.
revision = '75813aa30d8'
down_revision = '2a578ca812f0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yt_team', sa.Column('ground', sa.String(length=40), nullable=True))
    op.add_column('yt_team', sa.Column('letter', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yt_team', 'letter')
    op.drop_column('yt_team', 'ground')
    ### end Alembic commands ###
